Improve the error message when a DAG tries to access the DB. (#48015)
Previously it just gave a rather opaque error:

> module 'airflow.settings' has no attribute 'engine'

This improves that so that hopefully the user knows what is going on and isn't
left wondering if there's a bug in Airflow.

GitOrigin-RevId: cc7d0345b3c862fe2c59d92748c664018a5a9cd3