Improve the Error message in Breeze for invalid params (#10980)
Changed `Is` to `Passed`

Before:

```

ERROR:  Allowed backend: [ sqlite mysql postgres ]. Is: 'dpostgres'.

Switch to supported value with --backend flag.
```

After:

```

ERROR:  Allowed backend: [ sqlite mysql postgres ]. Passed: 'dpostgres'.

Switch to supported value with --backend flag.
```

GitOrigin-RevId: e066260ef8b7c12884ee95174cc64db7bab4bc16