Restrict google-cloud-texttospeach to <v2 (#9137)
Version 2 of this library causes the following pylint errors:

> airflow/providers/google/cloud/hooks/text_to_speech.py:59:27: E1123: Unexpected keyword argument 'client_info' in constructor call (unexpected-keyword-arg)
> airflow/providers/google/cloud/hooks/text_to_speech.py:99:15: E1123: Unexpected keyword argument 'input_' in method call (unexpected-keyword-arg)

(cherry picked from commit aa8990031d15b5c5b66fd9fb4b483d938e656bde)

GitOrigin-RevId: 19f6065eca7b8ec2525b1e9ffa0ef0452a80fa8c