Bugfix: Fix rendering of ``object_name`` in ``GCSToLocalFilesystemOperator`` (#15487)
https://github.com/apache/airflow/pull/14918 made coms consistency changes
where the template_fields was changed for ``GCSToLocalFilesystemOperator``.

While the change was correct since``object`` param was deprecated, the
instance attribute wasn't updated hence you see this error:

```
AttributeError: 'GCSToLocalFilesystemOperator' object has no attribute 'object_name'
```
GitOrigin-RevId: 3b9a91806ea102cc2bc00b545f63f57031f458c9