Revert "[AIRFLOW-626] HTML Content does not show up when sending email with attachment"
This reverts commit 55af3e04f8aa2062715370c8feec10308938715e.

Master is currently broken as shown on https://travis-ci.org/apache/incubator-airflow/jobs/175858834

======================================================================
FAIL: test_custom_backend (tests.EmailTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apache/incubator-airflow/tests/core.py", line 1927, in test_custom_backend
    send_email_test.assert_called_with('to', 'subject', 'content', files=None, dryrun=False, cc=None, bcc=None)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: mock('to', 'subject', 'content', bcc=None, cc=None, dryrun=False, files=None)
Actual call: mock('to', 'subject', 'content', bcc=None, cc=None, dryrun=False, files=None, mime_subtype=u'mixed')
GitOrigin-RevId: c6dd4d4578918364da1cd3d5655a8d41a65871b5