Fix flaky sqlite tests with `test_xcom_map_nest` hopefully (#33145)
Recently sqlite started to fail randomly during teardown of
`test_xcom_map_nest` or `test_xcom_map_zip_nest`. This happpened
after adding `test_xcom_map_zip_nest` . It looked very strange:

```
sqlite3.ProgrammingError: SQLite objects created in a thread can only be
used in that same thread
```

By analysing possible reasons it seems that it was a side effect
of the existing `test_xcom_map_nest` that allocated a new
session in the run method of task instance rather than pass
the sesion that is created and torrn down in the pytest fixture.

The hypothesis is that the session created in the ``test_xcom_map_nest``
were being reclaimed and closed while the `test_xcom_map_zip_nest` test
was already starting in a different thread started by Pytest.

The fix is to pass the session object to run method of the taskinstance
in the ``test_xcom_map_nest`` test.

(cherry picked from commit d1d6fc994d46aaed9c801162595cae91a1ffc19c)

GitOrigin-RevId: 4e817c46b4c94d44b5c50665f23f19d7284b42be