[AIRFLOW-2536] docs about how to deal with airflow initdb failure
Add docs to faq.rst to talk about how to deal with
Exception: Global variable
explicit_defaults_for_timestamp needs to be on (1)
for mysql

Closes #3429 from milton0825/fix-docs

GitOrigin-RevId: d5d97dc9719fd71625d8d252315ec01c7415c11a