Bump `uv` to `0.4.22` (#43056)
https://pypi.org/project/uv/0.4.22

I added `--no-sources` to our `uv pip install` command, without it, it fails with following error

```
error: Failed to build: `apache-airflow @ file:///dist/apache_airflow-3.0.0.dev0.tar.gz`
  Caused by: Failed to parse entry for: `local-providers`
  Caused by: Package is not included as workspace package in `tool.uv.workspace`
```
Example: https://github.com/apache/airflow/actions/runs/11354720505/job/31582868760#step:11:2896
GitOrigin-RevId: 5101b7ea785651f81f7dc6d676ed017e7e1c1caf