Fix Incorrect Example (#28609)
Following the existing example to create a decorator results in this error:
AttributeError: 'list' object has no attribute 'rsplit'

Changing it to a list fixes this

(cherry picked from commit 761aa59f9256fb2901039ac8ef7fd6e69af8528f)

GitOrigin-RevId: 652c6acd528f6391655e4a13f53e6944514c1561