BugFix: ``TimeSensorAsync`` returns a naive datetime (#17875)
My fix in https://github.com/apache/airflow/pull/17748 was only partially correct and I missed one part. `TimeSensorAsync` passed a naive datetime which failed when passed to `DateTimeTrigger`. This PR fixes it and adds test to avoid regression.

Error:

```
[2021-08-27 23:31:11,508] {taskinstance.py:1657} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/airflow/models/taskinstance.py", line 1296, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1415, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1471, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/airflow/sensors/time_sensor.py", line 60, in execute
    trigger=DateTimeTrigger(moment=self.target_datetime),
  File "/opt/airflow/airflow/triggers/temporal.py", line 40, in __init__
    raise ValueError("You cannot pass naive datetimes")
ValueError: You cannot pass naive datetimes
```

Example DAG:

```python
from datetime import timedelta, time

from airflow import DAG
from airflow.sensors.time_sensor import TimeSensorAsync
from airflow.utils import dates, timezone

with DAG(
    dag_id='example_date_time_async_operator',
    schedule_interval='0 0 * * *',
    start_date=dates.days_ago(2),
    dagrun_timeout=timedelta(minutes=60),
    tags=['example', 'example2', 'async'],
) as dag:

    TimeSensorAsync(task_id="test-2", target_time=time(0, 38, 0))

```

GitOrigin-RevId: 332406dae9f6b08de0d43576c4ed176eb49b8ed0