Fix typo introduced in #55125 (#55329)
```
error: unexpected argument '--no-python-download' found
tip: a similar argument exists: '--no-python-downloads'
```
GitOrigin-RevId: 4b8fbb3a6caf3d01c724473393f991fd6cd38ba9