Suppress deprecation warning when unpacking context in default_event_handler of MSGraphAsyncOperator (#47069)
* refactor: Make a copy of context items as dict to avoid deprecation warnings when unpacking in default_event_handler method of MSGraphAsyncOperator

* refactor: Updated TestMSGraphAsyncOperator

* refactor: Try to ignore the TypeError on warns(None)

* refactor: Use warnings.catch_warnings(record=True) instead of pytest.warn(None) to avoid TypeError: exceptions must be derived from Warning, not <class 'NoneType'>

* refactor: Don't copy context but suppress warnings message instead

* refactor: Forgot to filter deprecation warnings

* refactor: Also filter UserWarnings as AirflowContextDeprecationWarning raise by Context extends from it

* refactor: Try to make import of AirflowContextDeprecationWarning cross Airflow version compatible

* refactor: Added openlineage module to Microsoft Azure provider

* refactor: Added microsoft.aure provider in selected-providers-list-as-string for trigger openlineage and related providers tests when Assets files changed

* refactor: Added microsoft.aure provider in docs-list-as-string for trigger openlineage and related providers tests when Assets files changed

* refactor: Adapted providers-test-types-list-as-strings-in-json

* refactor: Added openlineage as optional dependency in provider_info

* refactor: Invert import of AirflowContextDeprecationWarning

* refactor: Redefine AirflowContextDeprecationWarning if Airflow 3 or higher

* Revert "refactor: Added openlineage as optional dependency in provider_info"

This reverts commit b8cdad5ba47c2d3825623b17b7fe67d7621dc0bf.

* Revert "refactor: Adapted providers-test-types-list-as-strings-in-json"

This reverts commit b4dbfc0407815dcc26721345022f94c8c1ae6746.

* Revert "refactor: Added microsoft.aure provider in docs-list-as-string for trigger openlineage and related providers tests when Assets files changed"

This reverts commit a3e6ac694d2709c78f3c9f1e094ed1e5ea8ada51.

* Revert "refactor: Added microsoft.aure provider in selected-providers-list-as-string for trigger openlineage and related providers tests when Assets files changed"

This reverts commit 32abded7af06b81460c8b1955f78458b5ca96ed4.

* refactor: Also filter UserWarnings

* refactor: Catch AttributeError instead of ImportError

* refactor: Try to satisfy mypy regarding AirflowContextDeprecationWarning

* refactor: Removed openlineage from README.rst

* refactor: Removed openlineage from pyproject.toml

* refactor: Handle AirflowContextDeprecationWarning directly within execute_callable method

* refactor: Ignore MyPy AttributeError

* refactor: Suppress AttributeError: module 'os' has no attribute 'register_at_fork' when running test on Windows machine

* refactor: Also suppress ImportError for AirflowContextDeprecationWarning in execute_callback

* refactor: Instead of suppressing AttributeError, which is dangerous, check platform instead and if not windows then register fork

* refactor: Reorganized imports settings

* refactor: Reformatted execute_callback

* refactor: Move mypy ignore one line up

---------

Co-authored-by: David Blain <david.blain@infrabel.be>
Co-authored-by: David Blain <david.blain@b-holding.be>
GitOrigin-RevId: 82f07ca115307e5452536643d8a94260bf918b53