Improve the error when DAG does not exist when running dag pause command (#13900)
When running `airflow dags unpause` with a DAG that does not exist, it
currently shows this error

```
root@6f086ba87198:/opt/airflow# airflow dags unpause example_bash_operatoredd
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/opt/airflow/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/airflow/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/airflow/airflow/cli/commands/dag_command.py", line 160, in dag_unpause
    set_is_paused(False, args)
  File "/opt/airflow/airflow/cli/commands/dag_command.py", line 170, in set_is_paused
    dag.set_is_paused(is_paused=is_paused)
AttributeError: 'NoneType' object has no attribute 'set_is_paused'
```

This commit changes the error to show a helpful error:

```
root@6f086ba87198:/opt/airflow# airflow dags unpause example_bash_operatoredd
DAG: example_bash_operatoredd does not exit in 'dag' table
```

(cherry picked from commit 8723b1feb82339d7a4ba5b40a6c4d4bbb995a4f9)

GitOrigin-RevId: 09e2c78eb25436911066a91ed9fa523fb8256a32