REST API: Fix wrong plugin schema (#34858)
* REST API: Fix wrong plugin schema

We serialize some plugin's fields as dictionaries leading to errors
when accessing the `/plugins` endpoint.

Here's the error:
ValueError: dictionary update sequence element #0 has length 1; 2 is required

The fields are lists of strings and this PR addresses it.

* fixup! REST API: Fix wrong plugin schema

* Add test at the endpoint

* fixup! Add test at the endpoint

(cherry picked from commit 474fa4ddfda231f336a2ae7b43fcbd3e349be5c9)

GitOrigin-RevId: 95c0154f675a136975f32999a89099775da9e82f