Fix XCom.delete error in Airflow 2.2.0 (#18956)
In Airflow 2.2.0 XCom.delete causes error, by trying to update dag_run table dag_id and execution_date columns to NULLs.

sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "dag_id" violates not-null constraint
[SQL: UPDATE dag_run SET dag_id=%(dag_id)s, execution_date=%(execution_date)s WHERE dag_run.id = %(dag_run_id)s]
[parameters: {'dag_id': None, 'execution_date': None, 'dag_run_id': 2409}]

Setting passive_deletes to the string value ‘all’ will disable the “nulling out”

(cherry picked from commit 47c5973b3d1ad6d492fb1ceff19d5ec43b8e74af)

GitOrigin-RevId: b329f8d3d71ead96f8ef7d5f6eb51f0525993b9d