Add Note to SLA regarding schedule_interval (#19173)
This document entry is intended to make explicit the requirement that SLAs will only be triggered for tasks in that are part of a scheduled DAG run.

Manually triggering DAGs with schedule_interval of None causes the error
```
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/dag_processing/processor.py", line 411, in manage_slas
    while dttm < timezone.utcnow():
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

And manually triggering DAGs with a valid schedule_interval do not produce tasks that can invoke an SLA Miss.  Only scheduled DAGs will check tasks for SLA misses.

GitOrigin-RevId: b18b2e502509fd492f65e18871b4db20f9e6cc4d