Fix passing Jinja templates in ``DateTimeSensor`` (#17959)
While fixing ``DateTimeSensorAsync`` in https://github.com/apache/airflow/pull/17747 -- I broke ``DateTimeSensor``.

As `target_time` is a template_field for `DateTimeSensor`, Jinja tries to render it which does not work if the input is a datetime object or if someone passes just a template field like ``{{ execution_date }} `` it throws an error:

```
    DateTimeSensor(task_id="foo",
                   target_time="{{ execution_time }}"
    )
    '
        Traceback (most recent call last):
          File "/usr/local/lib/python3.9/site-packages/pendulum/parsing/__init__.py", line 131, in _parse
            dt = parser.parse(
          File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1368, in parse
            return DEFAULTPARSER.parse(timestr, **kwargs)
          File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 643, in parse
            raise ParserError("Unknown string format: %s", timestr)
        dateutil.parser._parser.ParserError: Unknown string format: {{ execution_time }}

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "<string>", line 3, in <module>
          File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 186, in apply_defaults
            result = func(self, *args, **kwargs)
          File "/usr/local/lib/python3.9/site-packages/airflow/sensors/date_time.py", line 66, in __init__
            self.target_time = timezone.parse(target_time)
          File "/usr/local/lib/python3.9/site-packages/airflow/utils/timezone.py", line 175, in parse
            return pendulum.parse(string, tz=timezone or TIMEZONE, strict=False)  # type: ignore
          File "/usr/local/lib/python3.9/site-packages/pendulum/parser.py", line 29, in parse
            return _parse(text, **options)
          File "/usr/local/lib/python3.9/site-packages/pendulum/parser.py", line 45, in _parse
            parsed = base_parse(text, **options)
          File "/usr/local/lib/python3.9/site-packages/pendulum/parsing/__init__.py", line 74, in parse
            return _normalize(_parse(text, **_options), **_options)
          File "/usr/local/lib/python3.9/site-packages/pendulum/parsing/__init__.py", line 135, in _parse
            raise ParserError("Invalid date string: {}".format(text))
        pendulum.parsing.exceptions.ParserError: Invalid date string: {{ execution_time }}
```

This PR fixes it by reverting change in `DateTimeSensor` and parses the string to datetime in `DateTimeSensorAsync.execute`

GitOrigin-RevId: fbdb6882e4789c55c751b8be466eed89945d3241