Feature/edge maintenance plugin beautification (#55348)
@dheerajturaga somehow I was not able to pugh to your repo directly git gave me an error :-(
```
error: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'github.com:dheerajturaga/airflow.git'
```
...anyway, another way around, openeing a draft PR here, can you cherry-pick the commits down to your PR?

The last commit [Rework maintenance dialog to be a dialog](https://github.com/apache/airflow/commit/7e6d13cf316711f286e3262fa8552b2d62ede965) has a problem though: Dialog is not opening, it makes a JS script error which is not much helpful:
```
Uncaught TypeError: can't access property "flushSync", ne is undefined
    R http://localhost:28080/edge_worker/static/main.umd.cjs:16
```

GitOrigin-RevId: 068f3fce84e1d75752a852ba714e12d8f33f6f4f