[AIRFLOW-4829] More descriptive exceptions for EMR sensors (#5452)
EMR sensors, including the EmrStepSensor and the EmrJobFlowSensor
don't include failure reasons in exceptions though they already
have that info in the boto3 response from the EMR api. This adds
that info to exceptions.

Example exception:

> AirflowException: EMR job failed for code: BOOTSTRAP_FAILURE with message Master instance (i-02c25cade3cbfc453) failed attempting to download bootstrap action 1 file from S3

(cherry picked from commit 06dba668b99d38f60854bb3ca1dc6dd1cd17991e)

GitOrigin-RevId: a853e9d6c1ab6692a116b6e8c0362f79c6b5db5d