Add missing types to FSHook (#24470)
Fix mypy error :
```
error: Call to untyped function "FSHook" in typed context  [no-untyped-call]
```

When using :
```python
fs_hook = FSHook(fs_conn_id)
```
GitOrigin-RevId: d4eeede1fa65d626c6ce0d17f2c3c61f6b003162