TESTING.rst: Fix typo in path (#25763)
Critical because the path does not exist and results in error.

    ERROR: file or directory not found: tests/chart

GitOrigin-RevId: f24e706ff7a84fd36ea39dc3399346c357d40bd9