Fix proper termination of gunicorn when it hangs (#30188)
During refactoring of the internal API background test, it was
found that the SIGKILL termination of gunicorn in case it was not
responding to SIGTERM (introduced in #11734) has never been working
properly. The code assumed that gunicorn_master_process was
of the subprocess.Popen type and used .poll() method to check if the
process is still running and it would issue sigkill in such case.

However the Process we have there is a psutil.Process and it has
no poll() method - instead we can use is_running() method, which
has the added advantage that is_running() is also checking if the
pid has not been reused by another process after terminating the
original gunicorn.

The result of it was this error:

```
AttributeError: 'Process' object has no attribute 'poll'
```

(cherry picked from commit fd2db8856b36556b77d277a63c38c666816429c3)

GitOrigin-RevId: 2a5a1c2e2e08f29ea6ec6201513b350bb707f543