Add missing types to FSHook (#24470)
Fix mypy error :
```
error: Call to untyped function "FSHook" in typed context  [no-untyped-call]
```

When using :
```python
fs_hook = FSHook(fs_conn_id)
```

(cherry picked from commit d4eeede1fa65d626c6ce0d17f2c3c61f6b003162)

GitOrigin-RevId: 5dca4fb64b4124400d93ebc538500963c662a451