Pin OpenAI Python client to <1.66.0 (#47643)
OpenAI provider Tests are failing with:

```
___ ERROR collecting providers/openai/tests/unit/openai/hooks/test_openai.py ___
ImportError while importing test module '/opt/airflow/providers/openai/tests/unit/openai/hooks/test_openai.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
providers/openai/tests/unit/openai/hooks/test_openai.py:25: in <module>
    from openai.types.beta import (
E   ImportError: cannot import name 'VectorStore' from 'openai.types.beta' (/usr/local/lib/python3.9/site-packages/openai/types/beta/__init__.py
```

This is due to https://github.com/openai/openai-python/pull/2175

GitOrigin-RevId: b364cf84f61d0a62b880832c0a1a1b6e05006f69