Remove worrying log message about redaction from the OpenLineage plugin (#31149)
The current published plugin calls `_redact_all` directly, so when we
added the `max_depth` parameter in 2.6 (precisely so it didn't need to
call this private function directly!) we broke that.

This change leads to some worrying logs appearing in task logs for
anyone with the plugin installed:

```
[2023-05-05, 11:56:17 BST] {utils.py:490} WARNING - Unable to redact []Error was: TypeError: SecretsMasker._redact_all() missing 1 required positional argument: 'max_depth'
[2023-05-05, 11:56:17 BST] {utils.py:490} WARNING - Unable to redact []Error was: TypeError: SecretsMasker._redact_all() missing 1 required positional argument: 'max_depth'
[2023-05-05, 11:56:17 BST] {utils.py:490} WARNING - Unable to redact NoneError was: TypeError: SecretsMasker._redact_all() missing 1 required positional argument: 'max_depth'
```

This patch makes that previous change backwards compatible for that with
no change in behaviour for new code.

(cherry picked from commit 25e315995e53afef83fe310426c29e3bea14cd27)

GitOrigin-RevId: 518f4e2153f858dc974fb58264fbb5ea912fd2df