Fix `enable_logging=True` not working in `DockerSwarmOperator` (#35677)
* Fixes #28452: "TaskInstances do not succeed when using enable_logging=True option in DockerSwarmOperator"
It introduces logging of Docker Swarm services which was previously not
working.

* tty=True/False to be chosen by the user as it was the case before this fix (#28452)

* Follow=true for logs will always result in tasks not ending. This is  standard and provided upstream by the Docker API.
Therefore in DockerSwarmOperator follow is always false.

* service_logs called multiple times as we continuously poll the Docker API for logs. As we indicated in the previous commmit,
the docker client malfunctions when we try to get the logs with follow=True. Therefore we make multiple calls to the API (every 2 seconds), to fetch the new logs.

* service_logs called multiple times. In this test the tasks increase (6 instead of 5) as we check if the service has terminated (+1). As this assertion makes less sense in a situation where we do multiple calls to the Docker API (polling), we might think of removing it or replacing it with something more suitable.

* Final commit of this PR marking the test case that validates logging in the Docker Swarm Operator. We log two times a different message and we assert that the two lines are given back in the logs in the expected sequence.

* Formatting ruff

* Reverting as Github actions don't run this test as a swarm node:

docker.errors.APIError: 503 Server Error for http+docker://localhost/v1.43/services/create: Service Unavailable ("This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.")

Revert "Final commit of this PR marking the test case that validates logging in the Docker Swarm Operator. We log two times a different message and we assert that the two lines are given back in the logs in the expected sequence."

This reverts commit 048ba1ece25fcd02c5ccc752d63759c76b098e44.

* Logging "since" timestamp to avoid memory issues
Fix for #28452

* Formatting - Fix for #28452

GitOrigin-RevId: 882108862dcaf08e7f5da519b3d186048d4ec7f9