[AIRFLOW-3779] Don't install enum34 backport when not needed (#4620)
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

Installing this in more recent versions causes a "AttributeError: module
'enum' has no attribute 'IntFlag'`" in re.py

GitOrigin-RevId: 7ebecd677d427e90e292cb7446d96227bd0d6ae1