Fix "airflow tasks render" cli command for mapped task instances (#28698)
The fix was to use the 'template_fields' attr directly since both mapped and unmapped
tasks now have that attribute.
I also had to use ti.task instead of the task from dag.get_task due to this error:
`AttributeError: 'DecoratedMappedOperator' object has no attribute 'templates_dict'` and
I wonder if this is a bug

(cherry picked from commit 1da17be37627385fed7fc06584d72e0abda6a1b5)

GitOrigin-RevId: b4d65eb0ed854f808e07e6bf5a118003fc6b662c