ensure task is skipped if missing sla (#16719)
* ensure task is skipped if missing sla

This protects against missing SLAs.

For instance, if a task does not have an SLA then it's possible this will result in an error like so:

TypeError: unsupported operand type(s) for +: 'DateTime' and 'NoneType'
  File "airflow/jobs/scheduler_job.py", line 565, in execute_callbacks
    self.manage_slas(dagbag.dags.get(request.dag_id))
  File "airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "airflow/jobs/scheduler_job.py", line 433, in manage_slas
    if following_schedule + task.sla < timezone.utcnow():

Here we simply skip tasks which do not have SLAs and avoid raising the exception in subsequent logic.

GitOrigin-RevId: 39c8a9cac54b1c37d318492ab70f18d4af0e1dfc